openai_api_key = "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"
anthropic_api_key = "k-ant-api03-wHzDBdqHqNqBLb3MOxUorlK7iKq72o8s1W0S5O9xuBkShnZvN3etFkr49RZTF515Kw7ofpTdX4Xj2G-oKT6GWQ-Gp6OhQAA"
cohere_api_key = "0OJ7PC4fm97P18FFdOlQ3FFq6ou5Jfcu9j37ThlU"