openai_api_key = "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"
anthropic_api_key = "k-ant-api03-wHzDBdqHqNqBLb3MOxUorlK7iKq72o8s1W0S5O9xuBkShnZvN3etFkr49RZTF515Kw7ofpTdX4Xj2G-oKT6GWQ-Gp6OhQAA"
cohere_api_key = "0OJ7PC4fm97P18FFdOlQ3FFq6ou5Jfcu9j37ThlU"
gemini_api_key = "AIzaSyAP1PoLJVlk_l-xCQhjQ62nYBmNy_9_Ey0"